BooMarble/BooMarble-BE

src/main/java/com/likelion/boomarble/domain/user/domain/CustomUserDetails.java
src/main/java/com/likelion/boomarble/domain/user/dto/UserSignUpRequestDto.java
src/main/java/com/likelion/boomarble/domain/user/service/CustomUserDetailsService.java
src/main/java/com/likelion/boomarble/domain/user/token/JwtTokenProvider.java
src/main/java/com/likelion/boomarble/global/config/SecurityConfig.java

- 권한 인증 관련 코드 수정했습니다.
- 순환 참조 오류를 해결하기 위해 CustomUserDetails 추가했습니다.
- UserSignUpRequestDto에서 기본생성자 관련 오류를 해결하기 위해 @NoArgsConstructor 어노테이션 추가했습니다.
- SecurityConfig에서 JwtAuthenticationFilter 추가했습니다.(JWT 인증 필터)
- 대학 정보 상세 조회 및 검색

Fix: JWT 관련 수정

---

src/main/java/com/likelion/boomarble/domain/community/controller/CommunityController.java
src/main/java/com/likelion/boomarble/domain/community/domain/Community.java
src/main/java/com/likelion/boomarble/domain/community/dto/CommunityCreateDTO.java
src/main/java/com/likelion/boomarble/domain/community/dto/CommunityListDTO.java
src/main/java/com/likelion/boomarble/domain/community/dto/CommunityTagMap.java
src/main/java/com/likelion/boomarble/domain/community/dto/CommunityViewDTO.java
src/main/java/com/likelion/boomarble/domain/community/repository/CommunityRepository.java
src/main/java/com/likelion/boomarble/domain/community/repository/CommunityTagRepository.java
src/main/java/com/likelion/boomarble/domain/community/service/CommunityService.java
src/main/java/com/likelion/boomarble/domain/community/service/CommunityServiceImpl.java
src/main/java/com/likelion/boomarble/domain/model/Tag.java
src/main/java/com/likelion/boomarble/domain/model/repository/TagRepository.java
src/main/java/com/likelion/boomarble/domain/user/domain/CustomUserDetails.java

- 커뮤니티 글 등록 기능을 구현했습니다.
- 커뮤니티 글 목록 조회 기능을 구현했습니다.
- 커뮤니티 글 목록 조회 필터링 기능을 추가하겠습니다.

Feat: 커뮤니티 글 등록, 목록 조회

---

src/main/java/com/likelion/boomarble/domain/model/Country.java
src/main/java/com/likelion/boomarble/domain/universityInfo/controller/UniversityInfoController.java
src/main/java/com/likelion/boomarble/domain/universityInfo/domain/UniversityInfo.java
src/main/java/com/likelion/boomarble/domain/universityInfo/dto/RegisterUniversityInfoDTO.java
src/main/java/com/likelion/boomarble/domain/universityInfo/dto/UniversityInfoDetailDTO.java
src/main/java/com/likelion/boomarble/domain/universityInfo/service/UniversityInfoService.java
src/main/java/com/likelion/boomarble/domain/universityInfo/service/UniversityInfoServiceImpl.java
src/main/java/com/likelion/boomarble/domain/universityInfo/specification/UniversityInfoSpecifications.java
src/main/java/com/likelion/boomarble/global/error/GlobalExceptionHandler.java

- 대학 정보 목록 조회에서 받는 국가랑 교환유형 파라미터 타입 변경 (String -> Enum)
- 학점이랑 ielts 타입을 float로 변경
- 종속 드롭다운 리스트를 위한 기능 구현
- 모의 지원

Chore: 대학 목록 리스트 조회에서 국가랑 교환유형 타입 변경

---

src/main/java/com/likelion/boomarble/domain/universityInfo/dto/UniversityNameDTO.java
src/main/java/com/likelion/boomarble/domain/universityInfo/dto/UniversityNameListDTO.java
src/main/java/com/likelion/boomarble/domain/universityInfo/repository/UniversityInfoRepository.java
src/main/java/com/likelion/boomarble/domain/universityInfo/service/UniversityInfoService.java
src/main/java/com/likelion/boomarble/domain/universityInfo/service/UniversityInfoServiceImpl.java
src/main/java/com/likelion/boomarble/global/controller/globalController.java

- 종속 드롭다운 리스트를 위한 기능 구현
- 드롭다운에서 국가를 선택했을 시 그 국가에 따른 대학만 보일 수 있도록 api 추가했습니다.
- 정보 탭 뿐만 아니라 후기, 커뮤니티에서도 필요할 거 같아서 global 안에 controller 패키지를 추가했습니다.
- 모의지원

Feat: 국가에 따른 대학 리스트 조회

---

src/main/java/com/likelion/boomarble/domain/community/controller/CommunityController.java
src/main/java/com/likelion/boomarble/domain/community/specification/CommunitySpecification.java

- community에 필터링 기능을 추가했습니다.
- 상세조회 기능을 추가할 예정입니다.

Chore: 필터링 기능 추가

---

src/main/java/com/likelion/boomarble/domain/community/controller/CommunityController.java
src/main/java/com/likelion/boomarble/domain/community/service/CommunityService.java
src/main/java/com/likelion/boomarble/domain/community/service/CommunityServiceImpl.java

- CommunityServiceImpl에 필터링 기능 관련 누락된 부분이 있어 수정하였습니다.
- 커뮤니티 글 상세조회 작업할 예정입니다.

Chore: 필터링 기능 추가(2)

---

src/main/java/com/likelion/boomarble/domain/community/controller/CommunityController.java
src/main/java/com/likelion/boomarble/domain/community/dto/CommunityDetailDTO.java
src/main/java/com/likelion/boomarble/domain/community/exception/CommunityNotFoundException.java
src/main/java/com/likelion/boomarble/domain/community/service/CommunityServiceImpl.java

- 상세조회 기능을 추가했습니다.
- 상세조회 시 해시태그가 추가되지 않은 상태입니다. 해시태그 추가하도록 하겠습니다.

Feat: 상세조회 기능 추가

---

src/main/java/com/likelion/boomarble/domain/review/exception/ReviewNotFoundException.java

feat: 리뷰 exception 추가

---

src/main/java/com/likelion/boomarble/global/config/WebConfig.java

Feat: CORS 설정

---

src/main/java/com/likelion/boomarble/domain/community/domain/Community.java
src/main/java/com/likelion/boomarble/domain/community/dto/CommunityCreateDTO.java
src/main/java/com/likelion/boomarble/domain/community/dto/CommunityDetailDTO.java
src/main/java/com/likelion/boomarble/domain/community/dto/CommunityViewDTO.java
src/main/java/com/likelion/boomarble/domain/community/service/CommunityServiceImpl.java

- 대학, 국가, 학기, 교환유형 필드를 해시태그 리스트에 추가했습니다.
- 프론트 의견에 따라 상세조회, 목록조회 json 형식을 수정할 예정입니다.

Feat: 대학, 국가, 학기, 교환유형 해시태그로 추가

---

src/main/java/com/likelion/boomarble/domain/community/domain/Community.java
src/main/java/com/likelion/boomarble/domain/review/domain/Review.java
src/main/java/com/likelion/boomarble/domain/review/dto/ReviewCreateDTO.java
src/main/java/com/likelion/boomarble/domain/review/dto/ReviewDetailDTO.java
src/main/java/com/likelion/boomarble/domain/universityInfo/domain/UniversityInfo.java

- 리뷰 입력 시 exType, Country 필드 삭제!

fix: DB 필드 수정, 리뷰 작성 사항 수정

---

src/main/java/com/likelion/boomarble/domain/community/domain/Community.java
src/main/java/com/likelion/boomarble/domain/review/domain/Review.java
src/main/java/com/likelion/boomarble/domain/review/dto/ReviewCreateDTO.java
src/main/java/com/likelion/boomarble/domain/review/dto/ReviewDetailDTO.java
src/main/java/com/likelion/boomarble/domain/universityInfo/domain/UniversityInfo.java

- 대학의 학기 정보를 표기하기 위한 semester 필드를 추가했습니다.

feat: universityInfo에 semester 필드 추가

---

src/main/java/com/likelion/boomarble/domain/community/controller/CommunityController.java
src/main/java/com/likelion/boomarble/domain/community/domain/Comment.java
src/main/java/com/likelion/boomarble/domain/community/dto/CommentRequestDTO.java
src/main/java/com/likelion/boomarble/domain/community/dto/CommentResponseDTO.java
src/main/java/com/likelion/boomarble/domain/community/repository/CommentCustomRepository.java
src/main/java/com/likelion/boomarble/domain/community/repository/CommentRepository.java
src/main/java/com/likelion/boomarble/domain/community/repository/CommentRepositoryImpl.java
src/main/java/com/likelion/boomarble/domain/community/service/CommentService.java
src/main/java/com/likelion/boomarble/domain/community/service/CommentServiceImpl.java
src/main/java/com/likelion/boomarble/domain/community/service/CommunityService.java
src/main/java/com/likelion/boomarble/domain/community/service/CommunityServiceImpl.java
src/main/java/com/likelion/boomarble/domain/model/repository/ScrapRepository.java
src/main/java/com/likelion/boomarble/domain/user/domain/BaseTimeEntity.java

- 댓글, 대댓글 기능을 추가했습니다.
- 스크랩 기능을 추가했습니다. 
- DTO를 작성할 때 사용되는 필드만 작성하는게 좋은지, 의미상 포함되어야 하는 필드는 모두 작성하는게 좋은지 궁금합니다!
- 소셜 로그인을 구현하겠습니다.

Feat: 댓글, 스크랩 기능 추가

---

src/main/java/com/likelion/boomarble/domain/community/controller/CommunityController.java
src/main/java/com/likelion/boomarble/domain/community/domain/Comment.java
src/main/java/com/likelion/boomarble/domain/community/domain/Community.java
src/main/java/com/likelion/boomarble/domain/community/repository/CommunityRepository.java
src/main/java/com/likelion/boomarble/domain/community/service/CommentService.java
src/main/java/com/likelion/boomarble/domain/community/service/CommentServiceImpl.java
src/main/java/com/likelion/boomarble/domain/community/service/CommunityService.java
src/main/java/com/likelion/boomarble/domain/community/service/CommunityServiceImpl.java

- 게시글 수정 및 삭제를 구현했습니다.
- 게시글 삭제 시 관련 댓글과 태그를 같이 삭제할 수 있도록 구현했습니다.
- 소셜 로그인을 구현하겠습니다.

Feat: 게시글 수정 및 삭제

---

src/main/java/com/likelion/boomarble/domain/review/domain/Review.java

- 리뷰 필드에서 내용이 길 것으로 예상되는 필드들을 TEXT로 변경했습니다

fix: 일부 필드를 TEXT로 업데이트

---

src/main/java/com/likelion/boomarble/domain/chat/repository/RedisRepository.java
src/main/java/com/likelion/boomarble/domain/model/dto/SearchRankResponseDTO.java
src/main/java/com/likelion/boomarble/domain/universityInfo/controller/UniversityInfoController.java
src/main/java/com/likelion/boomarble/domain/universityInfo/service/UniversityInfoServiceImpl.java
src/main/java/com/likelion/boomarble/global/config/RedisConfig.java
src/main/java/com/likelion/boomarble/global/config/SecurityConfig.java
src/main/java/com/likelion/boomarble/global/config/WebSocketConfig.java
src/main/java/com/likelion/boomarble/global/controller/FileUploadController.java
src/main/java/com/likelion/boomarble/global/controller/globalController.java
src/main/java/com/likelion/boomarble/global/handler/StompHandler.java
src/main/java/com/likelion/boomarble/global/service/RedisService.java

- 인기검색어를 구현했습니다.
- websocker config를 작성했습니다.
- 커뮤니티 검색 구현 완료되면, 인기검색어 로직에 포함시키겠습니다.
- 채팅

Feat: 인기검색어 구현

---

build.gradle

- 챗봇 구현을 위해 필요한 라이브러리를 추가했습니다.

feat: json-simple 추가

---

src/main/java/com/likelion/boomarble/domain/community/service/CommunityServiceImpl.java
src/main/java/com/likelion/boomarble/global/service/RedisService.java

- 커뮤니티 검색 시 키워드가 레디스에 저장
- 마이페이지

Feat: 커뮤니티 검색에 인기검색어 로직 추가

---

src/main/java/com/likelion/boomarble/domain/universityInfo/service/UniversityInfoService.java
src/main/java/com/likelion/boomarble/domain/universityInfo/service/UniversityInfoServiceImpl.java
src/main/java/com/likelion/boomarble/global/controller/globalController.java

Feat: 드롭다운 내 검색 기능 구현

---

src/main/java/com/likelion/boomarble/domain/review/dto/ReviewAccGradeDTO.java
src/main/java/com/likelion/boomarble/domain/review/dto/ReviewActivityDTO.java
src/main/java/com/likelion/boomarble/domain/review/dto/ReviewCommonDTO.java
src/main/java/com/likelion/boomarble/domain/review/dto/ReviewCostDTO.java
src/main/java/com/likelion/boomarble/domain/review/dto/ReviewDormDTO.java
src/main/java/com/likelion/boomarble/domain/review/dto/ReviewEtcDTO.java
src/main/java/com/likelion/boomarble/domain/review/dto/ReviewMessageDTO.java
src/main/java/com/likelion/boomarble/domain/review/dto/ReviewPrepDTO.java
src/main/java/com/likelion/boomarble/domain/review/dto/ReviewSubjectsDTO.java
src/main/java/com/likelion/boomarble/domain/review/dto/ReviewUnivInfoDTO.java

fix: 리뷰 리스트에서 각 객체에 아이디를 추가했습니다

---

src/main/java/com/likelion/boomarble/domain/user/controller/OAuthController.java
src/main/java/com/likelion/boomarble/domain/user/domain/User.java
src/main/java/com/likelion/boomarble/domain/user/service/OAuthService.java
src/main/java/com/likelion/boomarble/domain/user/service/UserServiceImpl.java
src/main/java/com/likelion/boomarble/global/config/SecurityConfig.java

- 소셜 로그인을 구현했습니다.
- 정렬(최신순, 인기순) 하겠습니다.

Feat: 소셜 로그인 구현

---

src/main/java/com/likelion/boomarble/domain/community/controller/CommunityController.java
src/main/java/com/likelion/boomarble/domain/community/domain/Community.java
src/main/java/com/likelion/boomarble/domain/community/dto/CommunityCreateDTO.java
src/main/java/com/likelion/boomarble/domain/community/repository/CommunityRepository.java
src/main/java/com/likelion/boomarble/domain/community/service/CommunityService.java
src/main/java/com/likelion/boomarble/domain/community/service/CommunityServiceImpl.java
src/main/java/com/likelion/boomarble/domain/user/controller/UserController.java
src/main/java/com/likelion/boomarble/domain/user/domain/User.java
src/main/java/com/likelion/boomarble/domain/user/service/UserService.java
src/main/java/com/likelion/boomarble/domain/user/service/UserServiceImpl.java

- 커뮤니티 태그 입력 방식을 String -> ArrayList<String>으로 바꿨습니다.
- 회원가입 후 닉네임 추가 입력 기능을 추가했습니다.

Feat: 커뮤니티 태그 입력 방식 변경 & 닉네임 추가 입력
